use std::{ffi::CStr, mem::size_of};

use ash::{Device, vk};

use crate::{
    protocol::{
        AntiAliasingQualitySettings, BloomQualitySettings, CameraEffects, CameraSnapshot,
        DebugViewMode, LightPacket, RenderFeatureToggles, RenderQualitySettings,
    },
    renderer::pipeline::shader_interface,
};

use super::{
    VulkanError,
    god_rays::frame_god_ray_sources,
    mesh::EmissiveLightUniforms,
    shader::{self, assets},
    swapchain_target::{LookupTexture, create_lookup_texture, destroy_lookup_texture},
};

const SHADER_ENTRY: &CStr = shader::ENTRY;
const VERTEX_SHADER: &[u8] = assets::POST_VERT;
const FRAGMENT_SHADER: &[u8] = assets::POST_FRAG;
const FAST_FRAGMENT_SHADER: &[u8] = assets::POST_FAST_FRAG;
const SMAA_FRAGMENT_SHADER: &[u8] = assets::POST_SMAA_FRAG;
const SMAA_EDGE_FRAGMENT_SHADER: &[u8] = assets::POST_SMAA_EDGES_FRAG;
const SMAA_WEIGHT_FRAGMENT_SHADER: &[u8] = assets::POST_SMAA_WEIGHTS_FRAG;
// These are the official 1x SMAA lookup tables (MIT licensed, generated by iryoku/smaa).
// Keeping them as raw bytes avoids a runtime DDS dependency and preserves the exact RG8/R8
// formats expected by the area/search equations in the reference implementation.
const SMAA_AREA_TEX: &[u8] = include_bytes!("../../../assets/smaa/area_tex.rg8");
const SMAA_SEARCH_TEX: &[u8] = include_bytes!("../../../assets/smaa/search_tex.r8");
const SMAA_AREA_TEX_WIDTH: u32 = 160;
const SMAA_AREA_TEX_HEIGHT: u32 = 560;
const SMAA_SEARCH_TEX_WIDTH: u32 = 64;
const SMAA_SEARCH_TEX_HEIGHT: u32 = 16;
const POST_SCENE_COLOR_BINDING: u32 = 0;
const POST_SCENE_DEPTH_BINDING: u32 = 1;
const POST_SCENE_NORMAL_ROUGHNESS_BINDING: u32 = 2;
const POST_SCENE_TRANSPARENT_NORMAL_ROUGHNESS_BINDING: u32 = 3;
const POST_BLOOM_BINDING: u32 = 4;
const POST_GOD_RAY_0_BINDING: u32 = 5;
const POST_GOD_RAY_1_BINDING: u32 = 6;
const POST_TAA_LINEAR_DEPTH_BINDING: u32 = 7;
const POST_TAA_NORMAL_BINDING: u32 = 8;

pub(super) struct PostPipeline {
    pipeline: vk::Pipeline,
    fast_pipeline: vk::Pipeline,
    pipeline_layout: vk::PipelineLayout,
    pass_set_layout: vk::DescriptorSetLayout,
    empty_set_layout: vk::DescriptorSetLayout,
    descriptor_pool: vk::DescriptorPool,
    descriptor_sets: Vec<vk::DescriptorSet>,
    color_sampler: vk::Sampler,
    data_sampler: vk::Sampler,
}

struct PostBuild<'a> {
    device: &'a Device,
    pipeline: Option<vk::Pipeline>,
    fast_pipeline: Option<vk::Pipeline>,
    pipeline_layout: Option<vk::PipelineLayout>,
    pass_set_layout: Option<vk::DescriptorSetLayout>,
    empty_set_layout: Option<vk::DescriptorSetLayout>,
    descriptor_pool: Option<vk::DescriptorPool>,
    descriptor_sets: Vec<vk::DescriptorSet>,
    color_sampler: Option<vk::Sampler>,
    data_sampler: Option<vk::Sampler>,
    finished: bool,
}

impl<'a> PostBuild<'a> {
    /// Starts a guarded post-pipeline build that cleans up unless `finish` consumes it.
    fn new(device: &'a Device) -> Self {
        Self {
            device,
            pipeline: None,
            fast_pipeline: None,
            pipeline_layout: None,
            pass_set_layout: None,
            empty_set_layout: None,
            descriptor_pool: None,
            descriptor_sets: Vec::new(),
            color_sampler: None,
            data_sampler: None,
            finished: false,
        }
    }

    /// Moves all successfully-created objects into the runtime pipeline owner.
    fn finish(mut self) -> PostPipeline {
        let pipeline = take_created(&mut self.pipeline, "post pipeline");
        let fast_pipeline = take_created(&mut self.fast_pipeline, "fast post pipeline");
        let pipeline_layout = take_created(&mut self.pipeline_layout, "post pipeline layout");
        let pass_set_layout = take_created(&mut self.pass_set_layout, "post pass set layout");
        let empty_set_layout = take_created(&mut self.empty_set_layout, "post empty set layout");
        let descriptor_pool = take_created(&mut self.descriptor_pool, "post descriptor pool");
        let descriptor_sets = std::mem::take(&mut self.descriptor_sets);
        let color_sampler = take_created(&mut self.color_sampler, "post color sampler");
        let data_sampler = take_created(&mut self.data_sampler, "post data sampler");
        self.finished = true;

        PostPipeline {
            pipeline,
            fast_pipeline,
            pipeline_layout,
            pass_set_layout,
            empty_set_layout,
            descriptor_pool,
            descriptor_sets,
            color_sampler,
            data_sampler,
        }
    }

    /// Returns the empty set layout after it has been created.
    fn empty_set_layout(&self) -> vk::DescriptorSetLayout {
        expect_created(self.empty_set_layout, "post empty set layout")
    }

    /// Returns the pass set layout after it has been created.
    fn pass_set_layout(&self) -> vk::DescriptorSetLayout {
        expect_created(self.pass_set_layout, "post pass set layout")
    }

    /// Returns the pipeline layout after it has been created.
    fn pipeline_layout(&self) -> vk::PipelineLayout {
        expect_created(self.pipeline_layout, "post pipeline layout")
    }

    /// Returns the descriptor pool after it has been created.
    fn descriptor_pool(&self) -> vk::DescriptorPool {
        expect_created(self.descriptor_pool, "post descriptor pool")
    }

    /// Returns the descriptor set after it has been allocated.
    /// Returns the color sampler after it has been created.
    fn color_sampler(&self) -> vk::Sampler {
        expect_created(self.color_sampler, "post color sampler")
    }

    /// Returns the metadata sampler after it has been created.
    fn data_sampler(&self) -> vk::Sampler {
        expect_created(self.data_sampler, "post data sampler")
    }
}

impl Drop for PostBuild<'_> {
    /// Releases partially-created post resources when creation fails.
    fn drop(&mut self) {
        if self.finished {
            return;
        }

        if let Some(pipeline) = self.pipeline.take() {
            destroy_pipeline(self.device, pipeline);
        }
        if let Some(pipeline) = self.fast_pipeline.take() {
            destroy_pipeline(self.device, pipeline);
        }
        if let Some(pool) = self.descriptor_pool.take() {
            destroy_descriptor_pool(self.device, pool);
        }
        if let Some(sampler) = self.data_sampler.take() {
            destroy_sampler(self.device, sampler);
        }
        if let Some(sampler) = self.color_sampler.take() {
            destroy_sampler(self.device, sampler);
        }
        if let Some(layout) = self.pipeline_layout.take() {
            destroy_pipeline_layout(self.device, layout);
        }
        if let Some(layout) = self.pass_set_layout.take() {
            destroy_descriptor_set_layout(self.device, layout);
        }
        if let Some(layout) = self.empty_set_layout.take() {
            destroy_descriptor_set_layout(self.device, layout);
        }
    }
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
struct PostPushConstants {
    white_balance: [f32; 4],
    camera: [f32; 4],
    depth: [f32; 4],
    ssao: [f32; 4],
    ssr: [f32; 4],
    aa: [f32; 4],
    bloom: [f32; 4],
    features: [f32; 4],
    god_ray_source0: [f32; 4],
    god_ray_color0: [f32; 4],
    god_ray_source1: [f32; 4],
    god_ray_color1: [f32; 4],
    temporal: [f32; 4],
    exposure: f32,
    contrast: f32,
    saturation: f32,
    enabled: f32,
}

pub(super) const POST_PUSH_CONSTANT_SIZE: u32 = size_of::<PostPushConstants>() as u32;

impl PostPushConstants {
    /// Packs camera, look, and renderer quality state into the fragment push-constant layout.
    fn new(
        camera_effects: CameraEffects,
        camera: CameraSnapshot,
        extent: vk::Extent2D,
        quality: RenderQualitySettings,
        has_transparent_scene_items: bool,
        god_ray_history_index: usize,
        directional_light: LightPacket,
        emissive_lights: EmissiveLightUniforms,
        debug_view_mode: DebugViewMode,
        jitter_pixels: [f32; 2],
        taa_stable_metadata_valid: bool,
    ) -> Self {
        let white_balance = camera_effects.white_balance();
        let ssao = quality.ssao();
        let ssr = quality.ssr();
        let anti_aliasing = quality.anti_aliasing();
        let bloom = quality.bloom();
        // Match the frame graph's explicit feature route. Continuous bloom/god-ray values remain
        // available to the selected path but do not choose that path by themselves.
        let volumetric = quality.features().volumetric_fog_enabled();
        let post = quality.post();
        let camera_params = Self::camera_params(camera, extent);
        let god_ray_sources =
            frame_god_ray_sources(camera, extent, quality, directional_light, emissive_lights);

        Self {
            // Alpha is unused by color grading; carry jitter NDC X so post can map its stable
            // output grid back to the current jittered scene metadata.
            white_balance: [
                white_balance[0],
                white_balance[1],
                white_balance[2],
                jitter_pixels[0] * 2.0 / extent.width.max(1) as f32,
            ],
            camera: camera_params,
            depth: Self::depth_params(camera),
            ssao: [
                ssao.intensity(),
                ssao.radius(),
                ssao.bias(),
                ssao.sample_count() as f32,
            ],
            ssr: [
                ssr.intensity(),
                ssr.max_steps() as f32,
                ssr.max_distance(),
                ssr.thickness(),
            ],
            aa: Self::aa_params(extent, anti_aliasing),
            bloom: Self::bloom_params(bloom),
            features: [
                if has_transparent_scene_items {
                    1.0
                } else {
                    0.0
                },
                god_ray_history_index.min(1) as f32,
                debug_view_mode as u32 as f32,
                jitter_pixels[1] * 2.0 / extent.height.max(1) as f32,
            ],
            god_ray_source0: if volumetric {
                [0.0; 4]
            } else {
                god_ray_sources[0].source
            },
            god_ray_color0: if volumetric {
                [0.0; 4]
            } else {
                god_ray_sources[0].color
            },
            god_ray_source1: if volumetric {
                [0.0; 4]
            } else {
                god_ray_sources[1].source
            },
            god_ray_color1: if volumetric {
                // Alpha > 1 marks the dedicated volumetric composite to post_god_rays.
                [0.0, 0.0, 0.0, 2.0]
            } else {
                god_ray_sources[1].color
            },
            // The renderer's production SMAA graph leaves temporal metadata disabled. A legacy
            // temporal caller can still opt into the stable attachments; otherwise post reads the
            // current raw scene depth/normal through `post_metadata_uv`.
            temporal: [
                if taa_stable_metadata_valid { 1.0 } else { 0.0 },
                quality.features().bits() as f32,
                0.0,
                0.0,
            ],
            exposure: camera_effects.exposure().value(),
            contrast: (camera_effects.contrast() * post.contrast()).clamp(0.25, 4.0),
            saturation: (camera_effects.saturation() * post.saturation()).clamp(0.0, 4.0),
            enabled: if camera_effects.enabled() { 1.0 } else { 0.0 },
        }
    }

    /// Packs perspective coefficients reused by view reconstruction and SSR reprojection.
    fn camera_params(camera: CameraSnapshot, extent: vk::Extent2D) -> [f32; 4] {
        let aspect = (extent.width as f32 / extent.height.max(1) as f32).max(0.0001);
        let tan_half_fov = (camera.fov_y_radians * 0.5).tan();
        let tan_half_fov = if tan_half_fov.is_finite() && tan_half_fov > 0.0001 {
            tan_half_fov
        } else {
            0.57735026
        };
        let f = 1.0 / tan_half_fov;
        let focal_x = f / aspect;
        let focal_y = -f;

        [focal_x, focal_y, 1.0 / focal_x, 1.0 / focal_y]
    }

    /// Packs reusable perspective depth constants for post-pass reconstruction.
    fn depth_params(camera: CameraSnapshot) -> [f32; 4] {
        let near = camera.near.max(0.0001);
        let far = camera.far.max(near + 0.001);
        [near, far, near * far, far - near]
    }

    /// Packs texel size and SMAA edge controls used by the post fragment shader.
    fn aa_params(extent: vk::Extent2D, anti_aliasing: AntiAliasingQualitySettings) -> [f32; 4] {
        [
            1.0 / extent.width.max(1) as f32,
            1.0 / extent.height.max(1) as f32,
            anti_aliasing.edge_threshold(),
            anti_aliasing.blend(),
        ]
    }

    /// Packs the single-pass bloom controls.
    fn bloom_params(bloom: BloomQualitySettings) -> [f32; 4] {
        [
            bloom.intensity(),
            bloom.threshold(),
            bloom.radius_pixels(),
            bloom.god_rays_intensity(),
        ]
    }

    /// Uses the one-sample composition shader when every composition effect is disabled by its
    /// packed runtime values. The three-pass SMAA chain is separate and therefore does not affect
    /// this selection. These comparisons intentionally match the Slang enable predicates.
    fn uses_fast_pipeline(self) -> bool {
        let features = RenderFeatureToggles::from_bits(self.temporal[1] as u32);
        let ssao_enabled = features.ssao_enabled() && self.ssao[0] > 0.0;
        let ssr_enabled = features.ssr_enabled() && self.ssr[0] > 0.0 && self.ssr[1] >= 1.0;
        let bloom_enabled = features.bloom_enabled() && self.bloom[0] > 0.0;
        let debug_view_enabled = self.features[2] > 0.0;
        let god_rays_enabled = features.god_rays_enabled()
            && (self.god_ray_color1[3] > 1.5
                || (self.bloom[3] > 0.0
                    && (self.god_ray_source0[3] > 0.0 || self.god_ray_source1[3] > 0.0)));

        !(ssao_enabled || ssr_enabled || bloom_enabled || god_rays_enabled || debug_view_enabled)
    }
}

impl PostPipeline {
    /// Creates the post-composition pipeline that samples scene color and writes `PostColor`.
    pub(super) fn create(
        device: &Device,
        render_pass: vk::RenderPass,
        scene_color_view: vk::ImageView,
        scene_depth_view: vk::ImageView,
        scene_normal_roughness_view: vk::ImageView,
        scene_transparent_normal_roughness_view: vk::ImageView,
        bloom_view: vk::ImageView,
        god_ray_history_views: [vk::ImageView; 2],
    ) -> Result<Self, VulkanError> {
        let mut build = PostBuild::new(device);
        build.empty_set_layout = Some(create_empty_set_layout(device)?);
        build.pass_set_layout = Some(create_pass_set_layout(device)?);
        build.pipeline_layout = Some(create_pipeline_layout(
            device,
            build.empty_set_layout(),
            build.pass_set_layout(),
        )?);
        build.color_sampler = Some(create_sampler(device, vk::Filter::LINEAR)?);
        build.data_sampler = Some(create_sampler(device, vk::Filter::NEAREST)?);
        build.descriptor_pool = Some(create_descriptor_pool(device)?);
        build.descriptor_sets =
            allocate_descriptor_sets(device, build.descriptor_pool(), build.pass_set_layout(), 1)?;
        update_descriptor_set(
            device,
            build.descriptor_sets[0],
            scene_color_view,
            scene_depth_view,
            scene_normal_roughness_view,
            scene_transparent_normal_roughness_view,
            bloom_view,
            god_ray_history_views,
            build.color_sampler(),
            build.data_sampler(),
        );
        build.pipeline = Some(create_post_pipeline(
            device,
            build.pipeline_layout(),
            render_pass,
            FRAGMENT_SHADER,
        )?);
        build.fast_pipeline = Some(create_post_pipeline(
            device,
            build.pipeline_layout(),
            render_pass,
            FAST_FRAGMENT_SHADER,
        )?);

        tracing::info!("created Vulkan full and fast post-composition pipelines");
        Ok(build.finish())
    }

    /// Records the full-screen post pass that resolves the scene color into the
    /// intermediate post-color target. The following dedicated SMAA chain consumes that complete
    /// result, so this pass never has to reconstruct neighbor colors itself.
    pub(super) fn draw(
        &self,
        device: &Device,
        command_buffer: vk::CommandBuffer,
        extent: vk::Extent2D,
        camera_effects: CameraEffects,
        camera: CameraSnapshot,
        quality: RenderQualitySettings,
        has_transparent_scene_items: bool,
        god_ray_history_index: usize,
        directional_light: LightPacket,
        emissive_lights: EmissiveLightUniforms,
        debug_view_mode: DebugViewMode,
        jitter_pixels: [f32; 2],
        taa_stable_metadata_valid: bool,
    ) {
        let viewports = [vk::Viewport::default()
            .x(0.0)
            .y(0.0)
            .width(extent.width as f32)
            .height(extent.height as f32)
            .min_depth(0.0)
            .max_depth(1.0)];
        let scissors = [vk::Rect2D::default()
            .offset(vk::Offset2D { x: 0, y: 0 })
            .extent(extent)];
        let descriptor_set = self.descriptor_sets[0];
        let descriptor_sets = [descriptor_set];
        let push = PostPushConstants::new(
            camera_effects,
            camera,
            extent,
            quality,
            has_transparent_scene_items,
            god_ray_history_index,
            directional_light,
            emissive_lights,
            debug_view_mode,
            jitter_pixels,
            taa_stable_metadata_valid,
        );
        let fast_path = push.uses_fast_pipeline();
        let pipeline = if fast_path {
            self.fast_pipeline
        } else {
            self.pipeline
        };
        let push_bytes = push_constant_bytes(&push);

        tracing::trace!(
            width = extent.width,
            height = extent.height,
            exposure = push.exposure,
            white_balance = ?push.white_balance,
            contrast = push.contrast,
            saturation = push.saturation,
            enabled = camera_effects.enabled(),
            ssao_intensity = push.ssao[0],
            ssao_slices = quality.ssao().slice_count(),
            ssao_steps_per_slice = quality.ssao().steps_per_slice(),
            ssao_depth_taps = quality.ssao().sample_budget(),
            ssr_intensity = push.ssr[0],
            ssr_steps = push.ssr[1],
            aa_threshold = push.aa[2],
            aa_blend = push.aa[3],
            bloom_intensity = push.bloom[0],
            bloom_threshold = push.bloom[1],
            bloom_radius = push.bloom[2],
            god_rays_intensity = push.bloom[3],
            feature_bits = push.temporal[1] as u32,
            debug_view = push.features[2],
            god_ray_source0 = ?push.god_ray_source0,
            god_ray_source1 = ?push.god_ray_source1,
            has_transparent_scene_items,
            fast_path,
            "recording Vulkan post pass"
        );

        // Safety: the command buffer is inside the post render pass, the pipeline is compatible
        // with that pass, and the descriptor set points at the live scene color image view.
        unsafe {
            device.cmd_bind_pipeline(command_buffer, vk::PipelineBindPoint::GRAPHICS, pipeline);
            device.cmd_set_viewport(command_buffer, 0, &viewports);
            device.cmd_set_scissor(command_buffer, 0, &scissors);
            device.cmd_bind_descriptor_sets(
                command_buffer,
                vk::PipelineBindPoint::GRAPHICS,
                self.pipeline_layout,
                shader_interface::PASS_SET,
                &descriptor_sets,
                &[],
            );
            device.cmd_push_constants(
                command_buffer,
                self.pipeline_layout,
                vk::ShaderStageFlags::FRAGMENT,
                0,
                push_bytes,
            );
            device.cmd_draw(command_buffer, 3, 1, 0, 0);
        }
    }

    /// Destroys all swapchain-dependent post resources.
    pub(super) fn destroy(self, device: &Device) {
        destroy_pipeline(device, self.fast_pipeline);
        destroy_pipeline(device, self.pipeline);
        destroy_descriptor_pool(device, self.descriptor_pool);
        destroy_sampler(device, self.data_sampler);
        destroy_sampler(device, self.color_sampler);
        destroy_pipeline_layout(device, self.pipeline_layout);
        destroy_descriptor_set_layout(device, self.pass_set_layout);
        destroy_descriptor_set_layout(device, self.empty_set_layout);
    }
}

#[repr(C)]
#[derive(Clone, Copy, Default)]
struct SmaaPushConstants {
    aa: [f32; 4],
    depth: [f32; 4],
    debug: [f32; 4],
}

impl SmaaPushConstants {
    fn new(
        extent: vk::Extent2D,
        anti_aliasing: AntiAliasingQualitySettings,
        anti_aliasing_enabled: bool,
        camera: CameraSnapshot,
        debug_view_mode: DebugViewMode,
    ) -> Self {
        let near = camera.near.max(0.0001);
        let far = camera.far.max(near + 0.001);
        Self {
            aa: [
                1.0 / extent.width.max(1) as f32,
                1.0 / extent.height.max(1) as f32,
                anti_aliasing.edge_threshold(),
                if debug_view_mode == DebugViewMode::Disabled {
                    anti_aliasing.blend()
                } else {
                    0.0
                },
            ],
            depth: [near, far, near * far, far - near],
            debug: [
                debug_view_mode as u32 as f32,
                if anti_aliasing_enabled { 1.0 } else { 0.0 },
                0.0,
                0.0,
            ],
        }
    }
}

/// Owns the canonical three-pass SMAA 1x chain.
///
/// The edge and weight attachments are persistent swapchain-sized targets. Keeping them explicit
/// mirrors the paper/reference implementation and lets F12 diagnostics inspect each stage.
pub(super) struct SmaaPipeline {
    edge_pipeline: vk::Pipeline,
    weight_pipeline: vk::Pipeline,
    blend_pipeline: vk::Pipeline,
    pipeline_layout: vk::PipelineLayout,
    pass_set_layout: vk::DescriptorSetLayout,
    empty_set_layout: vk::DescriptorSetLayout,
    descriptor_pool: vk::DescriptorPool,
    descriptor_set: vk::DescriptorSet,
    color_sampler: vk::Sampler,
    area_sampler: vk::Sampler,
    area_texture: LookupTexture,
    search_texture: LookupTexture,
}

struct SmaaBuild<'a> {
    device: &'a Device,
    edge_pipeline: Option<vk::Pipeline>,
    weight_pipeline: Option<vk::Pipeline>,
    blend_pipeline: Option<vk::Pipeline>,
    pipeline_layout: Option<vk::PipelineLayout>,
    pass_set_layout: Option<vk::DescriptorSetLayout>,
    empty_set_layout: Option<vk::DescriptorSetLayout>,
    descriptor_pool: Option<vk::DescriptorPool>,
    descriptor_set: Option<vk::DescriptorSet>,
    color_sampler: Option<vk::Sampler>,
    area_sampler: Option<vk::Sampler>,
    area_texture: Option<LookupTexture>,
    search_texture: Option<LookupTexture>,
    finished: bool,
}

impl<'a> SmaaBuild<'a> {
    fn new(device: &'a Device) -> Self {
        Self {
            device,
            edge_pipeline: None,
            weight_pipeline: None,
            blend_pipeline: None,
            pipeline_layout: None,
            pass_set_layout: None,
            empty_set_layout: None,
            descriptor_pool: None,
            descriptor_set: None,
            color_sampler: None,
            area_sampler: None,
            area_texture: None,
            search_texture: None,
            finished: false,
        }
    }

    fn finish(mut self) -> SmaaPipeline {
        let edge_pipeline = take_created(&mut self.edge_pipeline, "SMAA edge pipeline");
        let weight_pipeline = take_created(&mut self.weight_pipeline, "SMAA weight pipeline");
        let blend_pipeline = take_created(&mut self.blend_pipeline, "SMAA blend pipeline");
        let pipeline_layout = take_created(&mut self.pipeline_layout, "SMAA pipeline layout");
        let pass_set_layout = take_created(&mut self.pass_set_layout, "SMAA pass set layout");
        let empty_set_layout = take_created(&mut self.empty_set_layout, "SMAA empty set layout");
        let descriptor_pool = take_created(&mut self.descriptor_pool, "SMAA descriptor pool");
        let descriptor_set = take_created(&mut self.descriptor_set, "SMAA descriptor set");
        let color_sampler = take_created(&mut self.color_sampler, "SMAA color sampler");
        let area_sampler = take_created(&mut self.area_sampler, "SMAA LUT sampler");
        let area_texture = self
            .area_texture
            .take()
            .expect("SMAA area texture was not created");
        let search_texture = self
            .search_texture
            .take()
            .expect("SMAA search texture was not created");
        self.finished = true;

        SmaaPipeline {
            edge_pipeline,
            weight_pipeline,
            blend_pipeline,
            pipeline_layout,
            pass_set_layout,
            empty_set_layout,
            descriptor_pool,
            descriptor_set,
            color_sampler,
            area_sampler,
            area_texture,
            search_texture,
        }
    }

    fn empty_set_layout(&self) -> vk::DescriptorSetLayout {
        expect_created(self.empty_set_layout, "SMAA empty set layout")
    }

    fn pass_set_layout(&self) -> vk::DescriptorSetLayout {
        expect_created(self.pass_set_layout, "SMAA pass set layout")
    }

    fn pipeline_layout(&self) -> vk::PipelineLayout {
        expect_created(self.pipeline_layout, "SMAA pipeline layout")
    }

    fn descriptor_pool(&self) -> vk::DescriptorPool {
        expect_created(self.descriptor_pool, "SMAA descriptor pool")
    }

    fn descriptor_set(&self) -> vk::DescriptorSet {
        expect_created(self.descriptor_set, "SMAA descriptor set")
    }

    fn color_sampler(&self) -> vk::Sampler {
        expect_created(self.color_sampler, "SMAA color sampler")
    }

    fn area_sampler(&self) -> vk::Sampler {
        expect_created(self.area_sampler, "SMAA LUT sampler")
    }
}

impl Drop for SmaaBuild<'_> {
    fn drop(&mut self) {
        if self.finished {
            return;
        }
        if let Some(pipeline) = self.blend_pipeline.take() {
            destroy_pipeline(self.device, pipeline);
        }
        if let Some(pipeline) = self.weight_pipeline.take() {
            destroy_pipeline(self.device, pipeline);
        }
        if let Some(pipeline) = self.edge_pipeline.take() {
            destroy_pipeline(self.device, pipeline);
        }
        if let Some(pool) = self.descriptor_pool.take() {
            destroy_descriptor_pool(self.device, pool);
        }
        if let Some(sampler) = self.color_sampler.take() {
            destroy_sampler(self.device, sampler);
        }
        if let Some(sampler) = self.area_sampler.take() {
            destroy_sampler(self.device, sampler);
        }
        if let Some(texture) = self.search_texture.take() {
            destroy_lookup_texture(self.device, texture);
        }
        if let Some(texture) = self.area_texture.take() {
            destroy_lookup_texture(self.device, texture);
        }
        if let Some(layout) = self.pipeline_layout.take() {
            destroy_pipeline_layout(self.device, layout);
        }
        if let Some(layout) = self.pass_set_layout.take() {
            destroy_descriptor_set_layout(self.device, layout);
        }
        if let Some(layout) = self.empty_set_layout.take() {
            destroy_descriptor_set_layout(self.device, layout);
        }
    }
}

impl SmaaPipeline {
    pub(super) fn create(
        device: &Device,
        memory_properties: &vk::PhysicalDeviceMemoryProperties,
        queue_family_index: u32,
        queue: vk::Queue,
        render_passes: [vk::RenderPass; 3],
        final_color_view: vk::ImageView,
        edges_view: vk::ImageView,
        weights_view: vk::ImageView,
    ) -> Result<Self, VulkanError> {
        let mut build = SmaaBuild::new(device);
        build.empty_set_layout = Some(create_empty_set_layout(device)?);
        build.pass_set_layout = Some(create_smaa_pass_set_layout(device)?);
        build.pipeline_layout = Some(create_smaa_pipeline_layout(
            device,
            build.empty_set_layout(),
            build.pass_set_layout(),
        )?);
        build.color_sampler = Some(create_sampler(device, vk::Filter::LINEAR)?);
        build.area_sampler = Some(create_sampler(device, vk::Filter::LINEAR)?);
        build.area_texture = Some(create_lookup_texture(
            device,
            memory_properties,
            queue_family_index,
            queue,
            SMAA_AREA_TEX_WIDTH,
            SMAA_AREA_TEX_HEIGHT,
            vk::Format::R8G8_UNORM,
            SMAA_AREA_TEX,
        )?);
        build.search_texture = Some(create_lookup_texture(
            device,
            memory_properties,
            queue_family_index,
            queue,
            SMAA_SEARCH_TEX_WIDTH,
            SMAA_SEARCH_TEX_HEIGHT,
            vk::Format::R8_UNORM,
            SMAA_SEARCH_TEX,
        )?);
        build.descriptor_pool = Some(create_smaa_descriptor_pool(device)?);
        build.descriptor_set = Some(
            allocate_descriptor_sets(device, build.descriptor_pool(), build.pass_set_layout(), 1)?
                .into_iter()
                .next()
                .expect("SMAA descriptor set was allocated"),
        );
        update_smaa_descriptor_set(
            device,
            build.descriptor_set(),
            final_color_view,
            edges_view,
            weights_view,
            build.color_sampler(),
            build.area_sampler(),
            build
                .area_texture
                .as_ref()
                .expect("SMAA area texture was just created")
                .view,
            build
                .search_texture
                .as_ref()
                .expect("SMAA search texture was just created")
                .view,
        );
        build.edge_pipeline = Some(create_post_pipeline(
            device,
            build.pipeline_layout(),
            render_passes[0],
            SMAA_EDGE_FRAGMENT_SHADER,
        )?);
        build.weight_pipeline = Some(create_post_pipeline(
            device,
            build.pipeline_layout(),
            render_passes[1],
            SMAA_WEIGHT_FRAGMENT_SHADER,
        )?);
        build.blend_pipeline = Some(create_post_pipeline(
            device,
            build.pipeline_layout(),
            render_passes[2],
            SMAA_FRAGMENT_SHADER,
        )?);

        tracing::info!("created Vulkan three-pass SMAA edge/weight/blend pipelines");
        Ok(build.finish())
    }

    fn draw_stage(
        &self,
        device: &Device,
        command_buffer: vk::CommandBuffer,
        extent: vk::Extent2D,
        anti_aliasing: AntiAliasingQualitySettings,
        anti_aliasing_enabled: bool,
        camera: CameraSnapshot,
        debug_view_mode: DebugViewMode,
        pipeline: vk::Pipeline,
        stage: &'static str,
    ) {
        let viewports = [vk::Viewport::default()
            .x(0.0)
            .y(0.0)
            .width(extent.width as f32)
            .height(extent.height as f32)
            .min_depth(0.0)
            .max_depth(1.0)];
        let scissors = [vk::Rect2D::default()
            .offset(vk::Offset2D { x: 0, y: 0 })
            .extent(extent)];
        let push = SmaaPushConstants::new(
            extent,
            anti_aliasing,
            anti_aliasing_enabled,
            camera,
            debug_view_mode,
        );
        let push_bytes = push_constant_bytes(&push);
        tracing::trace!(
            width = extent.width,
            height = extent.height,
            aa_threshold = push.aa[2],
            aa_blend = push.aa[3],
            aa_enabled = push.debug[1] > 0.5,
            debug_view = ?debug_view_mode,
            stage,
            "recording SMAA stage"
        );

        // Safety: the command buffer is inside the render pass selected by the caller and all
        // descriptor views belong to this swapchain and remain shader-readable for the stage.
        unsafe {
            device.cmd_bind_pipeline(command_buffer, vk::PipelineBindPoint::GRAPHICS, pipeline);
            device.cmd_set_viewport(command_buffer, 0, &viewports);
            device.cmd_set_scissor(command_buffer, 0, &scissors);
            let descriptor_sets = [self.descriptor_set];
            device.cmd_bind_descriptor_sets(
                command_buffer,
                vk::PipelineBindPoint::GRAPHICS,
                self.pipeline_layout,
                shader_interface::PASS_SET,
                &descriptor_sets,
                &[],
            );
            device.cmd_push_constants(
                command_buffer,
                self.pipeline_layout,
                vk::ShaderStageFlags::FRAGMENT,
                0,
                push_bytes,
            );
            device.cmd_draw(command_buffer, 3, 1, 0, 0);
        }
    }

    pub(super) fn draw_edges(
        &self,
        device: &Device,
        command_buffer: vk::CommandBuffer,
        extent: vk::Extent2D,
        anti_aliasing: AntiAliasingQualitySettings,
        anti_aliasing_enabled: bool,
        camera: CameraSnapshot,
    ) {
        self.draw_stage(
            device,
            command_buffer,
            extent,
            anti_aliasing,
            anti_aliasing_enabled,
            camera,
            DebugViewMode::Disabled,
            self.edge_pipeline,
            "edge_detection",
        );
    }

    pub(super) fn draw_weights(
        &self,
        device: &Device,
        command_buffer: vk::CommandBuffer,
        extent: vk::Extent2D,
        anti_aliasing: AntiAliasingQualitySettings,
        anti_aliasing_enabled: bool,
        camera: CameraSnapshot,
    ) {
        self.draw_stage(
            device,
            command_buffer,
            extent,
            anti_aliasing,
            anti_aliasing_enabled,
            camera,
            DebugViewMode::Disabled,
            self.weight_pipeline,
            "weight_calculation",
        );
    }

    pub(super) fn draw_blend(
        &self,
        device: &Device,
        command_buffer: vk::CommandBuffer,
        extent: vk::Extent2D,
        anti_aliasing: AntiAliasingQualitySettings,
        anti_aliasing_enabled: bool,
        camera: CameraSnapshot,
        debug_view_mode: DebugViewMode,
    ) {
        self.draw_stage(
            device,
            command_buffer,
            extent,
            anti_aliasing,
            anti_aliasing_enabled,
            camera,
            debug_view_mode,
            self.blend_pipeline,
            "neighborhood_blending",
        );
    }

    pub(super) fn destroy(self, device: &Device) {
        destroy_pipeline(device, self.blend_pipeline);
        destroy_pipeline(device, self.weight_pipeline);
        destroy_pipeline(device, self.edge_pipeline);
        destroy_descriptor_pool(device, self.descriptor_pool);
        destroy_sampler(device, self.color_sampler);
        destroy_sampler(device, self.area_sampler);
        destroy_lookup_texture(device, self.search_texture);
        destroy_lookup_texture(device, self.area_texture);
        destroy_pipeline_layout(device, self.pipeline_layout);
        destroy_descriptor_set_layout(device, self.pass_set_layout);
        destroy_descriptor_set_layout(device, self.empty_set_layout);
    }
}

/// Creates the five sampled-image bindings shared by all three SMAA passes and its LUTs.
fn create_smaa_pass_set_layout(device: &Device) -> Result<vk::DescriptorSetLayout, VulkanError> {
    let bindings = [
        post_sampler_binding(0),
        post_sampler_binding(1),
        post_sampler_binding(2),
        post_sampler_binding(3),
        post_sampler_binding(4),
    ];
    let create_info = vk::DescriptorSetLayoutCreateInfo::default().bindings(&bindings);

    // Safety: descriptor binding data is local and lives for the duration of the call.
    unsafe { device.create_descriptor_set_layout(&create_info, None) }.map_err(VulkanError::Vk)
}

/// Creates a pipeline layout matching the stable renderer set numbering and SMAA push constants.
fn create_smaa_pipeline_layout(
    device: &Device,
    empty_set_layout: vk::DescriptorSetLayout,
    pass_set_layout: vk::DescriptorSetLayout,
) -> Result<vk::PipelineLayout, VulkanError> {
    let mut set_layouts = [empty_set_layout; 3];
    set_layouts[shader_interface::PASS_SET as usize] = pass_set_layout;
    let push_range = vk::PushConstantRange::default()
        .stage_flags(vk::ShaderStageFlags::FRAGMENT)
        .offset(0)
        .size(size_of::<SmaaPushConstants>() as u32);
    let push_ranges = [push_range];
    let create_info = vk::PipelineLayoutCreateInfo::default()
        .set_layouts(&set_layouts)
        .push_constant_ranges(&push_ranges);

    // Safety: descriptor set layouts and push constant ranges live for this call.
    unsafe { device.create_pipeline_layout(&create_info, None) }.map_err(VulkanError::Vk)
}

/// Creates the descriptor pool for the three-pass SMAA inputs.
fn create_smaa_descriptor_pool(device: &Device) -> Result<vk::DescriptorPool, VulkanError> {
    let pool_sizes = [vk::DescriptorPoolSize::default()
        .ty(vk::DescriptorType::COMBINED_IMAGE_SAMPLER)
        .descriptor_count(5)];
    let create_info = vk::DescriptorPoolCreateInfo::default()
        .max_sets(1)
        .pool_sizes(&pool_sizes);

    // Safety: pool sizes are local values.
    unsafe { device.create_descriptor_pool(&create_info, None) }.map_err(VulkanError::Vk)
}

/// Writes the post image, intermediate edge/weight targets, and lookup textures into the SMAA
/// descriptor shared by the three passes.
fn update_smaa_descriptor_set(
    device: &Device,
    descriptor_set: vk::DescriptorSet,
    final_color_view: vk::ImageView,
    edges_view: vk::ImageView,
    weights_view: vk::ImageView,
    color_sampler: vk::Sampler,
    area_sampler: vk::Sampler,
    area_texture_view: vk::ImageView,
    search_texture_view: vk::ImageView,
) {
    let color_info = [post_image_info(color_sampler, final_color_view)];
    let edges_info = [post_image_info(color_sampler, edges_view)];
    let weights_info = [post_image_info(color_sampler, weights_view)];
    let area_info = [post_image_info(area_sampler, area_texture_view)];
    let search_info = [post_image_info(area_sampler, search_texture_view)];
    let writes = [
        vk::WriteDescriptorSet::default()
            .dst_set(descriptor_set)
            .dst_binding(0)
            .descriptor_type(vk::DescriptorType::COMBINED_IMAGE_SAMPLER)
            .image_info(&color_info),
        vk::WriteDescriptorSet::default()
            .dst_set(descriptor_set)
            .dst_binding(1)
            .descriptor_type(vk::DescriptorType::COMBINED_IMAGE_SAMPLER)
            .image_info(&edges_info),
        vk::WriteDescriptorSet::default()
            .dst_set(descriptor_set)
            .dst_binding(2)
            .descriptor_type(vk::DescriptorType::COMBINED_IMAGE_SAMPLER)
            .image_info(&weights_info),
        vk::WriteDescriptorSet::default()
            .dst_set(descriptor_set)
            .dst_binding(3)
            .descriptor_type(vk::DescriptorType::COMBINED_IMAGE_SAMPLER)
            .image_info(&area_info),
        vk::WriteDescriptorSet::default()
            .dst_set(descriptor_set)
            .dst_binding(4)
            .descriptor_type(vk::DescriptorType::COMBINED_IMAGE_SAMPLER)
            .image_info(&search_info),
    ];

    // Safety: descriptor set, samplers, and image views belong to this device and remain alive.
    unsafe {
        device.update_descriptor_sets(&writes, &[]);
    }
}

/// Creates the descriptor set layout used by the post shader's scene textures.
fn create_pass_set_layout(device: &Device) -> Result<vk::DescriptorSetLayout, VulkanError> {
    let bindings = [
        post_sampler_binding(POST_SCENE_COLOR_BINDING),
        post_sampler_binding(POST_SCENE_DEPTH_BINDING),
        post_sampler_binding(POST_SCENE_NORMAL_ROUGHNESS_BINDING),
        post_sampler_binding(POST_SCENE_TRANSPARENT_NORMAL_ROUGHNESS_BINDING),
        post_sampler_binding(POST_BLOOM_BINDING),
        post_sampler_binding(POST_GOD_RAY_0_BINDING),
        post_sampler_binding(POST_GOD_RAY_1_BINDING),
        post_sampler_binding(POST_TAA_LINEAR_DEPTH_BINDING),
        post_sampler_binding(POST_TAA_NORMAL_BINDING),
    ];
    let create_info = vk::DescriptorSetLayoutCreateInfo::default().bindings(&bindings);

    // Safety: descriptor binding data is local and lives for the duration of the call.
    unsafe { device.create_descriptor_set_layout(&create_info, None) }.map_err(VulkanError::Vk)
}

/// Creates one sampled-image binding for the post pass descriptor set.
fn post_sampler_binding(binding: u32) -> vk::DescriptorSetLayoutBinding<'static> {
    vk::DescriptorSetLayoutBinding::default()
        .binding(binding)
        .descriptor_type(vk::DescriptorType::COMBINED_IMAGE_SAMPLER)
        .descriptor_count(1)
        .stage_flags(vk::ShaderStageFlags::FRAGMENT)
}

/// Creates an empty descriptor set layout for unused frame/material slots.
fn create_empty_set_layout(device: &Device) -> Result<vk::DescriptorSetLayout, VulkanError> {
    let create_info = vk::DescriptorSetLayoutCreateInfo::default();

    // Safety: no pointers are stored after the call.
    unsafe { device.create_descriptor_set_layout(&create_info, None) }.map_err(VulkanError::Vk)
}

/// Creates a pipeline layout that keeps frame/material/pass set order stable.
fn create_pipeline_layout(
    device: &Device,
    empty_set_layout: vk::DescriptorSetLayout,
    pass_set_layout: vk::DescriptorSetLayout,
) -> Result<vk::PipelineLayout, VulkanError> {
    let mut set_layouts = [empty_set_layout; 3];
    set_layouts[shader_interface::PASS_SET as usize] = pass_set_layout;
    let push_range = vk::PushConstantRange::default()
        .stage_flags(vk::ShaderStageFlags::FRAGMENT)
        .offset(0)
        .size(size_of::<PostPushConstants>() as u32);
    let push_ranges = [push_range];
    let create_info = vk::PipelineLayoutCreateInfo::default()
        .set_layouts(&set_layouts)
        .push_constant_ranges(&push_ranges);

    // Safety: descriptor set layouts and push constant ranges live for this call.
    unsafe { device.create_pipeline_layout(&create_info, None) }.map_err(VulkanError::Vk)
}

/// Creates one post-pass sampler with explicit filtering for color or metadata images.
fn create_sampler(device: &Device, filter: vk::Filter) -> Result<vk::Sampler, VulkanError> {
    let create_info = vk::SamplerCreateInfo::default()
        .mag_filter(filter)
        .min_filter(filter)
        .mipmap_mode(vk::SamplerMipmapMode::NEAREST)
        .address_mode_u(vk::SamplerAddressMode::CLAMP_TO_EDGE)
        .address_mode_v(vk::SamplerAddressMode::CLAMP_TO_EDGE)
        .address_mode_w(vk::SamplerAddressMode::CLAMP_TO_EDGE)
        .min_lod(0.0)
        .max_lod(0.0);

    // Safety: sampler create info contains only local values.
    unsafe { device.create_sampler(&create_info, None) }.map_err(VulkanError::Vk)
}

/// Creates the descriptor pool for post-process sampled image bindings.
fn create_descriptor_pool(device: &Device) -> Result<vk::DescriptorPool, VulkanError> {
    let pool_sizes = [vk::DescriptorPoolSize::default()
        .ty(vk::DescriptorType::COMBINED_IMAGE_SAMPLER)
        .descriptor_count(9)];
    let create_info = vk::DescriptorPoolCreateInfo::default()
        .max_sets(1)
        .pool_sizes(&pool_sizes);

    // Safety: pool sizes are local values.
    unsafe { device.create_descriptor_pool(&create_info, None) }.map_err(VulkanError::Vk)
}

/// Allocates the descriptor set bound by the post pass.
fn allocate_descriptor_sets(
    device: &Device,
    descriptor_pool: vk::DescriptorPool,
    pass_set_layout: vk::DescriptorSetLayout,
    count: usize,
) -> Result<Vec<vk::DescriptorSet>, VulkanError> {
    let layouts = vec![pass_set_layout; count];
    let allocate_info = vk::DescriptorSetAllocateInfo::default()
        .descriptor_pool(descriptor_pool)
        .set_layouts(&layouts);

    // Safety: the descriptor pool and set layout are alive for allocation.
    unsafe { device.allocate_descriptor_sets(&allocate_info) }.map_err(VulkanError::Vk)
}

/// Writes sampled scene color, depth, and normal/roughness images into the post descriptor set.
fn update_descriptor_set(
    device: &Device,
    descriptor_set: vk::DescriptorSet,
    scene_color_view: vk::ImageView,
    scene_depth_view: vk::ImageView,
    scene_normal_roughness_view: vk::ImageView,
    scene_transparent_normal_roughness_view: vk::ImageView,
    bloom_view: vk::ImageView,
    god_ray_history_views: [vk::ImageView; 2],
    color_sampler: vk::Sampler,
    data_sampler: vk::Sampler,
) {
    let color_info = [post_image_info(color_sampler, scene_color_view)];
    let depth_info = [post_image_info(data_sampler, scene_depth_view)];
    let normal_roughness_info = [post_image_info(data_sampler, scene_normal_roughness_view)];
    let transparent_normal_roughness_info = [post_image_info(
        data_sampler,
        scene_transparent_normal_roughness_view,
    )];
    let bloom_info = [post_image_info(color_sampler, bloom_view)];
    let god_ray_0_info = [post_image_info(color_sampler, god_ray_history_views[0])];
    let god_ray_1_info = [post_image_info(color_sampler, god_ray_history_views[1])];
    // TAA is no longer part of the production AA path. Keep these bindings valid by pointing
    // them at the current MRTs; the shader only selects them when stable temporal metadata is
    // explicitly enabled by a legacy caller.
    let taa_depth_info = [post_image_info(data_sampler, scene_depth_view)];
    let taa_normal_info = [post_image_info(data_sampler, scene_normal_roughness_view)];
    let writes = [
        vk::WriteDescriptorSet::default()
            .dst_set(descriptor_set)
            .dst_binding(POST_SCENE_COLOR_BINDING)
            .descriptor_type(vk::DescriptorType::COMBINED_IMAGE_SAMPLER)
            .image_info(&color_info),
        vk::WriteDescriptorSet::default()
            .dst_set(descriptor_set)
            .dst_binding(POST_SCENE_DEPTH_BINDING)
            .descriptor_type(vk::DescriptorType::COMBINED_IMAGE_SAMPLER)
            .image_info(&depth_info),
        vk::WriteDescriptorSet::default()
            .dst_set(descriptor_set)
            .dst_binding(POST_SCENE_NORMAL_ROUGHNESS_BINDING)
            .descriptor_type(vk::DescriptorType::COMBINED_IMAGE_SAMPLER)
            .image_info(&normal_roughness_info),
        vk::WriteDescriptorSet::default()
            .dst_set(descriptor_set)
            .dst_binding(POST_SCENE_TRANSPARENT_NORMAL_ROUGHNESS_BINDING)
            .descriptor_type(vk::DescriptorType::COMBINED_IMAGE_SAMPLER)
            .image_info(&transparent_normal_roughness_info),
        vk::WriteDescriptorSet::default()
            .dst_set(descriptor_set)
            .dst_binding(POST_BLOOM_BINDING)
            .descriptor_type(vk::DescriptorType::COMBINED_IMAGE_SAMPLER)
            .image_info(&bloom_info),
        vk::WriteDescriptorSet::default()
            .dst_set(descriptor_set)
            .dst_binding(POST_GOD_RAY_0_BINDING)
            .descriptor_type(vk::DescriptorType::COMBINED_IMAGE_SAMPLER)
            .image_info(&god_ray_0_info),
        vk::WriteDescriptorSet::default()
            .dst_set(descriptor_set)
            .dst_binding(POST_GOD_RAY_1_BINDING)
            .descriptor_type(vk::DescriptorType::COMBINED_IMAGE_SAMPLER)
            .image_info(&god_ray_1_info),
        vk::WriteDescriptorSet::default()
            .dst_set(descriptor_set)
            .dst_binding(POST_TAA_LINEAR_DEPTH_BINDING)
            .descriptor_type(vk::DescriptorType::COMBINED_IMAGE_SAMPLER)
            .image_info(&taa_depth_info),
        vk::WriteDescriptorSet::default()
            .dst_set(descriptor_set)
            .dst_binding(POST_TAA_NORMAL_BINDING)
            .descriptor_type(vk::DescriptorType::COMBINED_IMAGE_SAMPLER)
            .image_info(&taa_normal_info),
    ];

    // Safety: descriptor set, sampler, and image view belong to this device and remain alive.
    unsafe {
        device.update_descriptor_sets(&writes, &[]);
    }
}

/// Builds one post-pass sampled-image descriptor with shader-read layout.
fn post_image_info(sampler: vk::Sampler, image_view: vk::ImageView) -> vk::DescriptorImageInfo {
    vk::DescriptorImageInfo::default()
        .sampler(sampler)
        .image_view(image_view)
        .image_layout(vk::ImageLayout::SHADER_READ_ONLY_OPTIMAL)
}

/// Returns a created handle from a build slot with a resource-specific panic message.
fn expect_created<T: Copy>(value: Option<T>, label: &'static str) -> T {
    value.unwrap_or_else(|| panic!("{label} was not created"))
}

/// Moves a created handle out of a build slot with a resource-specific panic message.
fn take_created<T>(value: &mut Option<T>, label: &'static str) -> T {
    value
        .take()
        .unwrap_or_else(|| panic!("{label} was not created"))
}

/// Creates the full-screen post graphics pipeline.
fn create_post_pipeline(
    device: &Device,
    pipeline_layout: vk::PipelineLayout,
    render_pass: vk::RenderPass,
    fragment_shader_code: &[u8],
) -> Result<vk::Pipeline, VulkanError> {
    let vertex_shader = shader::create_shader_module(device, VERTEX_SHADER)?;
    let fragment_shader = match shader::create_shader_module(device, fragment_shader_code) {
        Ok(shader) => shader,
        Err(error) => {
            shader::destroy_shader_module(device, vertex_shader);
            return Err(error);
        }
    };
    let pipeline = create_graphics_pipeline(
        device,
        pipeline_layout,
        render_pass,
        vertex_shader,
        fragment_shader,
    );

    shader::destroy_shader_module(device, fragment_shader);
    shader::destroy_shader_module(device, vertex_shader);
    pipeline
}

/// Creates fixed-function state for a full-screen triangle post pass.
fn create_graphics_pipeline(
    device: &Device,
    pipeline_layout: vk::PipelineLayout,
    render_pass: vk::RenderPass,
    vertex_shader: vk::ShaderModule,
    fragment_shader: vk::ShaderModule,
) -> Result<vk::Pipeline, VulkanError> {
    let shader_stages = [
        vk::PipelineShaderStageCreateInfo::default()
            .stage(vk::ShaderStageFlags::VERTEX)
            .module(vertex_shader)
            .name(SHADER_ENTRY),
        vk::PipelineShaderStageCreateInfo::default()
            .stage(vk::ShaderStageFlags::FRAGMENT)
            .module(fragment_shader)
            .name(SHADER_ENTRY),
    ];
    let vertex_input = vk::PipelineVertexInputStateCreateInfo::default();
    let input_assembly = vk::PipelineInputAssemblyStateCreateInfo::default()
        .topology(vk::PrimitiveTopology::TRIANGLE_LIST);
    let viewport_state = vk::PipelineViewportStateCreateInfo::default()
        .viewport_count(1)
        .scissor_count(1);
    let rasterization = vk::PipelineRasterizationStateCreateInfo::default()
        .polygon_mode(vk::PolygonMode::FILL)
        .cull_mode(vk::CullModeFlags::NONE)
        .front_face(vk::FrontFace::CLOCKWISE)
        .line_width(1.0);
    let multisample = vk::PipelineMultisampleStateCreateInfo::default()
        .rasterization_samples(vk::SampleCountFlags::TYPE_1);
    let color_blend_attachment = vk::PipelineColorBlendAttachmentState::default().color_write_mask(
        vk::ColorComponentFlags::R
            | vk::ColorComponentFlags::G
            | vk::ColorComponentFlags::B
            | vk::ColorComponentFlags::A,
    );
    let color_blend_attachments = [color_blend_attachment];
    let color_blend =
        vk::PipelineColorBlendStateCreateInfo::default().attachments(&color_blend_attachments);
    let dynamic_states = [vk::DynamicState::VIEWPORT, vk::DynamicState::SCISSOR];
    let dynamic_state =
        vk::PipelineDynamicStateCreateInfo::default().dynamic_states(&dynamic_states);
    let pipeline_info = vk::GraphicsPipelineCreateInfo::default()
        .stages(&shader_stages)
        .vertex_input_state(&vertex_input)
        .input_assembly_state(&input_assembly)
        .viewport_state(&viewport_state)
        .rasterization_state(&rasterization)
        .multisample_state(&multisample)
        .color_blend_state(&color_blend)
        .dynamic_state(&dynamic_state)
        .layout(pipeline_layout)
        .render_pass(render_pass)
        .subpass(0);
    let pipeline_infos = [pipeline_info];

    // Safety: pipeline state references are local and render pass compatibility is fixed.
    match unsafe {
        device.create_graphics_pipelines(vk::PipelineCache::null(), &pipeline_infos, None)
    } {
        Ok(mut pipelines) => Ok(pipelines.remove(0)),
        Err((pipelines, error)) => {
            for pipeline in pipelines {
                destroy_pipeline(device, pipeline);
            }
            Err(VulkanError::Vk(error))
        }
    }
}

/// Views a push-constant struct as bytes for Vulkan command recording.
fn push_constant_bytes<T>(value: &T) -> &[u8] {
    // Safety: push constants are plain repr(C) data and are copied during command recording.
    unsafe { std::slice::from_raw_parts((value as *const T).cast::<u8>(), size_of::<T>()) }
}

/// Destroys one descriptor set layout.
fn destroy_descriptor_set_layout(device: &Device, layout: vk::DescriptorSetLayout) {
    if layout != vk::DescriptorSetLayout::null() {
        // Safety: descriptor set layouts are destroyed after dependent objects.
        unsafe { device.destroy_descriptor_set_layout(layout, None) };
    }
}

/// Destroys one pipeline layout.
fn destroy_pipeline_layout(device: &Device, layout: vk::PipelineLayout) {
    if layout != vk::PipelineLayout::null() {
        // Safety: all pipelines using this layout are destroyed first.
        unsafe { device.destroy_pipeline_layout(layout, None) };
    }
}

/// Destroys one descriptor pool and descriptor sets allocated from it.
fn destroy_descriptor_pool(device: &Device, pool: vk::DescriptorPool) {
    if pool != vk::DescriptorPool::null() {
        // Safety: descriptor sets from this pool are no longer in use.
        unsafe { device.destroy_descriptor_pool(pool, None) };
    }
}

/// Destroys one sampler.
fn destroy_sampler(device: &Device, sampler: vk::Sampler) {
    if sampler != vk::Sampler::null() {
        // Safety: the sampler was created by this device and is no longer referenced.
        unsafe { device.destroy_sampler(sampler, None) };
    }
}

/// Destroys one graphics pipeline.
fn destroy_pipeline(device: &Device, pipeline: vk::Pipeline) {
    if pipeline != vk::Pipeline::null() {
        // Safety: the pipeline was created by this device and is no longer referenced.
        unsafe { device.destroy_pipeline(pipeline, None) };
    }
}

#[cfg(test)]
mod tests {
    use super::{
        PostPushConstants, SMAA_AREA_TEX, SMAA_AREA_TEX_HEIGHT, SMAA_AREA_TEX_WIDTH,
        SMAA_SEARCH_TEX, SMAA_SEARCH_TEX_HEIGHT, SMAA_SEARCH_TEX_WIDTH,
    };
    use crate::protocol::RenderFeatureToggles;

    #[test]
    fn smaa_lookup_payloads_match_reference_dimensions() {
        assert_eq!(
            SMAA_AREA_TEX.len(),
            (SMAA_AREA_TEX_WIDTH * SMAA_AREA_TEX_HEIGHT * 2) as usize
        );
        assert_eq!(
            SMAA_SEARCH_TEX.len(),
            (SMAA_SEARCH_TEX_WIDTH * SMAA_SEARCH_TEX_HEIGHT) as usize
        );
    }

    #[test]
    fn fast_post_requires_every_expensive_feature_to_be_disabled() {
        let disabled = PostPushConstants::default();
        assert!(disabled.uses_fast_pipeline());

        // SMAA is a separate three-pass chain, so enabling it does not force the composition
        // shader off its one-sample fast path.
        let mut aa = disabled;
        aa.aa[3] = 1.0;
        assert!(aa.uses_fast_pipeline());

        let mut ssao = disabled;
        ssao.temporal[1] = RenderFeatureToggles::disabled().with_ssao(true).bits() as f32;
        ssao.ssao[0] = 1.0;
        assert!(!ssao.uses_fast_pipeline());

        let mut ssr = disabled;
        ssr.temporal[1] = RenderFeatureToggles::disabled().with_ssr(true).bits() as f32;
        ssr.ssr[0] = 1.0;
        ssr.ssr[1] = 1.0;
        assert!(!ssr.uses_fast_pipeline());

        let mut bloom = disabled;
        bloom.temporal[1] = RenderFeatureToggles::disabled().with_bloom(true).bits() as f32;
        bloom.bloom[0] = 1.0;
        assert!(!bloom.uses_fast_pipeline());

        let mut god_rays = disabled;
        god_rays.temporal[1] = RenderFeatureToggles::disabled().with_god_rays(true).bits() as f32;
        god_rays.bloom[3] = 1.0;
        god_rays.god_ray_source1[3] = 1.0;
        assert!(!god_rays.uses_fast_pipeline());

        let mut debug_view = disabled;
        debug_view.features[2] = 1.0;
        assert!(!debug_view.uses_fast_pipeline());
    }

    #[test]
    fn fast_post_matches_compound_shader_enable_conditions() {
        let mut ssr_without_steps = PostPushConstants::default();
        ssr_without_steps.ssr[0] = 1.0;
        assert!(ssr_without_steps.uses_fast_pipeline());

        let mut god_rays_without_source = PostPushConstants::default();
        god_rays_without_source.bloom[3] = 1.0;
        assert!(god_rays_without_source.uses_fast_pipeline());
    }
}
