use std::{ffi::CStr, io::Cursor};

use ash::{Device, util, vk};

use super::VulkanError;

pub(super) const ENTRY: &CStr = c"main";

pub(super) mod assets {
    include!(concat!(env!("OUT_DIR"), "/shader_assets.rs"));
}

/// Creates one Vulkan shader module from build-script compiled SPIR-V bytes.
pub(super) fn create_shader_module(
    device: &Device,
    bytes: &[u8],
) -> Result<vk::ShaderModule, VulkanError> {
    let code = util::read_spv(&mut Cursor::new(bytes)).map_err(VulkanError::ShaderCodeRead)?;
    let create_info = vk::ShaderModuleCreateInfo::default().code(&code);

    // Safety: SPIR-V bytes are generated by build.rs and copied into a local word vector.
    unsafe { device.create_shader_module(&create_info, None) }.map_err(VulkanError::Vk)
}

/// Destroys one temporary shader module after graphics pipeline creation has finished.
pub(super) fn destroy_shader_module(device: &Device, shader: vk::ShaderModule) {
    if shader != vk::ShaderModule::null() {
        // Safety: the module was created by this device and is no longer referenced.
        unsafe { device.destroy_shader_module(shader, None) };
    }
}
